EventManager/MVC/Models/OradorViewModels.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace MVC.Models
{
    public class OradorVm : PersonaVm
    {
        //Propiedades

        [Required(AllowEmptyStrings = false, ErrorMessage = "El campo {0} es obligatorio.")]
        [StringLength(100, ErrorMessage = "El campo {0} no debe superar los {1} caracteres.")]
        public new string Nombre { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "El campo {0} es obligatorio.")]
        [StringLength(100, ErrorMessage = "El campo {0} no debe superar los {1} caracteres.")]
        public new string Apellido { get; set; }

        [Display(Name = "Nombre")]
        public string ApyNom
        {
            get
            {
                return Nombre + " " + Apellido;
            }
        }

        [Required(AllowEmptyStrings = false, ErrorMessage = "El campo {0} es obligatorio.")]
        [StringLength(11, ErrorMessage = "El campo {0} no debe superar los {1} caracteres.")]
        public string Cuil { get; set; }

        [Required(ErrorMessage = "El campo {0} es obligatorio")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime FechaNacimiento { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "El campo {0} es obligatorio.")]
        public string Genero { get; set; }

        [StringLength(11, ErrorMessage = "El campo {0} no debe superar los {1} caracteres.")]
        public string Telefono { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "El campo {0} es obligatorio")]
        [StringLength(10, ErrorMessage = "El campo {0} no debe superar los {1} caractere")]
        public string Celular { get; set; }

        public bool Estado { get; set; }

        [Display(Name = "Provincia")]
        public long ProvinciaId { get; set; }

        [Display(Name = "Provincia")]
        public string ProvinciaStr { get; set; }

        [Display(Name = "Ciudad")]
        public long CiudadId { get; set; }

        [Display(Name = "Ciudad")]
        public string CiudadStr { get; set; }

        public long? EventoId { get; set; } //se usa en evento asignarorador

        public string EstadoStr { get; set; }

        public bool EventosAsociados { get; set; }
    }
}

EventManager/MVC/Controllers/OradorController.cs
using Infraestructura;
using IServicio.Ciudad;
using IServicio.Evento;
using IServicio.Orador;
using IServicio.Orador.Dto;
using MVC.Helpers.ComboBox.Ciudad;
using MVC.Helpers.ComboBox.Provincia;
using MVC.Helpers.ComboBox.Sexo;
using MVC.Models;
using Rotativa;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web.Mvc;

namespace MVC.Controllers
{
    public class OradorController : Controller
    {
        private EventManagerContext db = new EventManagerContext();

        private readonly IOradorServicio _oradorServicio;
        private readonly IEventoServicio _eventoServicio;
        private readonly IComboBoxProvincia _comboBoxProvincia;
        private readonly IComboBoxCiudad _comboBoxCiudad;
        private readonly IComboBoxSexo _comboBoxSexo;
        private readonly ICiudadServicio _ciudadServicio;


        public OradorController()
        {

        }

        public OradorController(IOradorServicio oradorServicio, IEventoServicio eventoServicio
                                , IComboBoxProvincia comboBoxProvincia, IComboBoxCiudad comboBoxCiudad
                                , ICiudadServicio ciudadServicio, IComboBoxSexo comboBoxSexo)
        {
            _oradorServicio = oradorServicio;
            _eventoServicio = eventoServicio;
            _comboBoxProvincia = comboBoxProvincia;
            _comboBoxCiudad = comboBoxCiudad;
            _ciudadServicio = ciudadServicio;
            _comboBoxSexo = comboBoxSexo;
        }

        // GET: Oradors
        public ActionResult Index(string cadenaBuscar)
        {
            var oradores = _oradorServicio.GetByFilter(!string.IsNullOrEmpty(cadenaBuscar) ? cadenaBuscar : string.Empty);

            var lista = new List<OradorVm>();

            foreach (var item in oradores)
            {
                var eventos = _eventoServicio.GetAll().Where(x => x.OradorId == item.Id);

                if (eventos.Count() > 0)
                {
                    var orador = new OradorVm()
                    {
                        Id = item.Id,
                        Apellido = item.Apellido,
                        Nombre = item.Nombre,
                        Celular = item.Celular,
                        FechaNacimiento = item.FechaNacimiento,
                        Genero = item.Genero,
                        Cuil = item.Cuil,
                        Estado = item.Estado,
                        EstadoStr = item.Estado ? "Activo" : "Inactivo",
                        Telefono = item.Telefono,
                        ProvinciaStr = item.ProvinciaStr,
                        CiudadStr = item.CiudadStr,
                        EventosAsociados = true
                    };

                    lista.Add(orador);
                }

                else
                {
                    var orador = new OradorVm()
                    {
                        Id = item.Id,
                        Apellido = item.Apellido,
                        Nombre = item.Nombre,
                        Celular = item.Celular,
                        FechaNacimiento = item.FechaNacimiento,
                        Genero = item.Genero,
                        Cuil = item.Cuil,
                        Estado = item.Estado,
                        EstadoStr = item.Estado ? "Activo" : "Inactivo",
                        Telefono = item.Telefono,
                        ProvinciaStr = item.ProvinciaStr,
                        CiudadStr = item.CiudadStr,
                        EventosAsociados = false
                    };

                    lista.Add(orador);
                }
            }

           

            return View(lista.Select(x => new OradorVm()
            {
                Id = x.Id,
                Apellido = x.Apellido,
                Nombre = x.Nombre,
                Celular = x.Celular,
                FechaNacimiento = x.FechaNacimiento,
                Genero = x.Genero,
                Cuil = x.Cuil,
                Estado = x.Estado,
                EstadoStr = x.Estado ? "Activo" : "Inactivo",
                Telefono = x.Telefono,
                ProvinciaStr = x.ProvinciaStr,
                CiudadStr = x.CiudadStr,
                EventosAsociados = x.EventosAsociados

            }).ToList());
        }

        // GET: Oradors/Details/5
        public ActionResult Details(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var orador = _oradorServicio.GetById(id);

            if (orador == null)
            {
                return HttpNotFound();
            }
            return View(new OradorVm()
            {
                Id = orador.Id,
                Apellido = orador.Apellido,
                Nombre = orador.Nombre,
                Celular = orador.Celular,
                FechaNacimiento = orador.FechaNacimiento,
                Genero = orador.Genero,
                Cuil = orador.Cuil,
                Estado = orador.Estado,
                Telefono = orador.Telefono,
                ProvinciaStr = orador.ProvinciaStr,
                CiudadStr = orador.CiudadStr
            });
        }

        // GET: Oradors/Create
        public ActionResult Create()
        {
            List<SelectListItem> listaCiudad = new List<SelectListItem>()
            {
            };

            return View(new OradorVm()
            {
                Provincias = _comboBoxProvincia.Poblar(),
                Ciudades = listaCiudad,
                Sexos = _comboBoxSexo.Poblar()
            });
        }

        // POST: Oradors/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(OradorVm oradorVm)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var oradorDto = CargarOradorDto(oradorVm);

                    _oradorServicio.Add(oradorDto);
                }
                return RedirectToAction("Index");

            }

            catch (Exception ex)
            {
                if (ex.InnerException != null &&
                            ex.InnerException.InnerException != null &&
                            ex.InnerException.InnerException.Message.Contains("_Index"))
                {
                    ModelState.AddModelError(string.Empty, "No se pudo crear el registro por que ya existe");
                }
                else
                {
                    ModelState.AddModelError(string.Empty, ex.Message);
                }
            }

            List<SelectListItem> listaCiudad = new List<SelectListItem>()
            {
            };


            return View(new OradorVm
            {
                Sexos = _comboBoxSexo.Poblar(),
                Provincias = _comboBoxProvincia.Poblar(),
                Ciudades = listaCiudad
            });

        }


        // GET: Oradors/Edit/5
        public ActionResult Edit(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var orador = _oradorServicio.GetById(id);

            if (orador == null)
            {
                return HttpNotFound();
            }
            return View(new OradorVm()
            {

                Apellido = orador.Apellido,
                Nombre = orador.Nombre,
                Celular = orador.Celular,
                FechaNacimiento = orador.FechaNacimiento,
                Genero = orador.Genero,
                Sexos = _comboBoxSexo.Poblar(),
                Cuil = orador.Cuil,
                Estado = orador.Estado,
                Telefono = orador.Telefono,
                ProvinciaId = orador.ProvinciaId,
                Provincias = _comboBoxProvincia.Poblar(),
                CiudadId = orador.CiudadId,
                Ciudades = _comboBoxCiudad.Poblar()

            });
        }

        // POST: Oradors/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(OradorVm oradorVm)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var orador = CargarOradorDto(oradorVm);

                    orador.Estado = oradorVm.Estado;

                    _oradorServicio.Update(orador);

                }

                return RedirectToAction("Index");

            }
            catch (Exception ex)
            {
                if (ex.InnerException != null &&
                            ex.InnerException.InnerException != null &&
                            ex.InnerException.InnerException.Message.Contains("_Index"))
                {
                    ModelState.AddModelError(string.Empty, "No se pudo crear el registro por que ya existe");
                }
                else
                {
                    ModelState.AddModelError(string.Empty, ex.Message);
                }
            }

            return View(new OradorVm
            {
                Sexos = _comboBoxSexo.Poblar(),
                Provincias = _comboBoxProvincia.Poblar(),
                Ciudades = _comboBoxCiudad.Poblar()
            });

        }

        // GET: Oradors/Delete/5
        public ActionResult Delete(long? id)
        {

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var orador = _oradorServicio.GetById(id);

            if (orador == null)
            {

EventManager/MVC/Views/Orador/AsignarOrador.cshtml
@model IEnumerable<MVC.Models.OradorVm>

@{
    Layout = null;
}

<h2>Orador</h2>

    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Apellido)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Cuil)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Estado)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Nombre)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Apellido)
                </td>
                <td style="color=">
                    @Html.DisplayFor(modelItem => item.Cuil)
                </td>
                <td style="color:@(item.Estado == true ? "blue" : "red" );">
                    <b>@Html.DisplayFor(modelItem => item.EstadoStr)</b>
                </td>

                <td>
                    @using (Html.BeginForm("AsignarOrador", "Orador", new {oradorId = item.Id, eventoId = item.EventoId }))
                    {
                        @Html.AntiForgeryToken()


                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <input type="submit" value="Asignar" class="btn btn-success" />
                            </div>
                        </div>
                    }

                    </td>
            </tr>

        }

    </table>

<br />

@Html.ActionLink("Cancelar", "AdministrarEvento", "Evento", new { id = ViewBag.EventoId }, new { @class = "btn btn-danger" })

EventManager/MVC/Views/Orador/Create.cshtml
@model MVC.Models.OradorVm

@{
    Layout = null;
    ViewBag.Title = "Nuevo Orador";
}

<h2>Crear</h2>


@using (Html.BeginForm("Create", "Orador", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Orador</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control", @required = "required" } })
                @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Apellido, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Apellido, new { htmlAttributes = new { @class = "form-control", @required = "required" } })
                @Html.ValidationMessageFor(model => model.Apellido, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Cuil, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Cuil, new { htmlAttributes = new { @class = "form-control", @required = "required" } })
                @Html.ValidationMessageFor(model => model.Cuil, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FechaNacimiento, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FechaNacimiento, new { htmlAttributes = new { @class = "form-control", @required = "required" } })
                @Html.ValidationMessageFor(model => model.FechaNacimiento, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Genero, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Genero, Model.Sexos, "[Seleccione sexo]", new { @class = "form-control", @required = "required" })
                @Html.ValidationMessageFor(model => model.Genero, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.Telefono, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Telefono, new { htmlAttributes = new { @class = "form-control", @required = "required" } })
                @Html.ValidationMessageFor(model => model.Telefono, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Celular, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Celular, new { htmlAttributes = new { @class = "form-control", @required = "required" } })
                @Html.ValidationMessageFor(model => model.Celular, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProvinciaId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.ProvinciaId, Model.Provincias, "Seleccione una Provincia", new { @class = "form-control", @required = "required" })
                @Html.ValidationMessageFor(model => model.ProvinciaId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CiudadId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.CiudadId, Model.Ciudades, "Seleccione una Ciudad", new { @class = "form-control", @required = "required" })
                @Html.ValidationMessageFor(model => model.CiudadId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Aceptar" class="btn btn-success" id="Aceptar" />

                @Html.ActionLink("Cancelar", "Index", new { }, new { @class = "btn btn-danger" })
            </div>
        </div>
    </div>
}

<script type="text/javascript">

  $(document).ready(function () {

    ////////////////////////////
    ////////Fecha Actual/////////
    ////////////////////////////

    n = new Date();
    //Año
    y = n.getFullYear();
    //Mes
    m = n.getMonth() + 1;
    //Día
    d = n.getDate();

    if (d < 10)
        d = '0' + d; //agrega cero si el menor de 10
    if (m < 10)
        m = '0' + m //agrega cero si el menor de 10

        var fechaActual = y + "-" + m + "-" + d;

          /////////////////////////////
         ////    Restricciones    ////
        /////////////////////////////

        $("#Nombre").blur(function () {

            $("#Nombre").val($.trim($("#Nombre").val()));

        });

        $("#Nombre").keypress(function (e) {

            if ((e.charCode < 97 || e.charCode > 122) && (e.charCode < 65 || e.charCode > 90) && (e.charCode != 32)) return false;
        });

        $("#Apellido").blur(function () {

            $("#Apellido").val($.trim($("#Apellido").val()));

        });

        $("#Apellido").keypress(function (e) {

            if ((e.charCode < 97 || e.charCode > 122) && (e.charCode < 65 || e.charCode > 90) && (e.charCode != 32)) return false;
        });


    $('#Cuil').keypress(function (e) {

        if (e.keyCode == 32) {
            return false;
        }

        if (event.which < 48 || event.which > 57 || this.value.length === 11) {
            return false;
        }
    });

        $("#FechaNacimiento").keypress(function (e) {


            if ((event.which < 97 || event.which > 122) && (event.which < 65 || event.which > 90)) {
                return false;
            }

        });

        $("#FechaNacimiento").change(function () {

            var fecha = $(this).val();

            if (fecha > fechaActual) {

                alert("La fecha de nacimiento (" + fecha + ") no puede ser despues de la fecha de hoy (" + fechaActual + ")")

                $("#FechaNacimiento").val(fechaActual);
            }
        });

    $('#Telefono').keypress(function (e) {

        if(e.keyCode == 32) {
            return false;
        }

        if (event.which < 48 || event.which > 57 || this.value.length === 11) {
            return false;
        }
    });

    $('#Celular').keypress(function (e) {

        if (e.keyCode == 32) {
            return false;
        }

        if (event.which < 48 || event.which > 57 || this.value.length === 10) {
            return false;
        }
    });

        $("#ProvinciaId").change(function () {
            $("#CiudadId").empty();
            $("#CiudadId").append('<option value="">Seleccione una ciudad</option>');
            $.ajax({
                type: 'POST',
                url: '@Url.Action("ObtenerCiudades")',
                dataType: 'json',
                data: { provinciaId: $("#ProvinciaId").val() },
                success: function (data) {
                    $.each(data, function (i, data) {
                        $("#CiudadId").append('<option value="'
                            + data.Id + '">'
                            + data.Nombre + '</option>');
                    });
                },
            });
            return false;
      })

      $("#Aceptar").click(function () {

          var validarFormCuil = $("#Cuil").val().length // validar Numero valido cuil

          if (validarFormCuil < 11) {
              alert("Debe ingresar un Numero de Cuil Valido")
              return false;
          }

          var validarFormTelefono = $("#Telefono").val().length // validar Numero valido Telefono

          if (validarFormTelefono < 11) {
              alert("Debe ingresar un Numero de Telefono Valido")
              return false;
          }

          var validarFormCelular = $("#Celular").val().length // validar Numero valido Celular

          if (validarFormCelular < 10) {
              alert("Debe ingresar un Numero de Celular Valido")
              return false;
          }

      });

  });

</script>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

EventManager/MVC/Views/Orador/Delete.cshtml
@model MVC.Models.OradorVm

@{
    Layout = null;
    ViewBag.Title = "Elimar";
}

<h3>seguro que desea eliminar este orador?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Apellido)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Apellido)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Cuil)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cuil)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FechaNacimiento)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FechaNacimiento)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Genero)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Genero)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Telefono)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Telefono)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Celular)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Celular)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Estado)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Estado)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProvinciaStr)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProvinciaStr)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CiudadStr)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CiudadStr)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Eliminar" class="btn btn-danger" /> 

            @Html.ActionLink("Cancelar", "Index", new { }, new { @class = "btn btn-info"})
        </div>
    }
</div>

EventManager/MVC/Views/Orador/Details.cshtml
@model MVC.Models.OradorVm

@{
    Layout = null;
    ViewBag.Title = "Detalle";
}

<h2>Detalle</h2>

<div>
    <h4>Orador</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Apellido)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Apellido)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Cuil)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cuil)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FechaNacimiento)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FechaNacimiento)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Genero)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Genero)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Telefono)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Telefono)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Celular)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Celular)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Estado)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Estado)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProvinciaStr)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProvinciaStr)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.CiudadStr)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CiudadStr)
        </dd>

    </dl>
</div>

EventManager/MVC/Views/Orador/Index.cshtml
@model IEnumerable<MVC.Models.OradorVm>

@{
    ViewBag.Title = "Oradores";
}
<link href="~/Content/Estilos/Reportes.css" rel="stylesheet" />
<h2>Oradores</h2>

<div class="col-lg-12">
    <p class="col-lg-2">
        <a id="btnCrearOrador" data-toggle="modal" href="#myModal" class="btn btn-primary btn-lg">Agregar</a>
    </p>
    <p class="col-lg-2 col-lg-offset-8">
        @Html.ActionLink("Imprimir", "Imprimir", "Orador", null, new { @class = "btn btn-danger" })
    </p>
</div>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Nombre)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Apellido)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Cuil)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FechaNacimiento)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Genero)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Telefono)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Celular)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Estado)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ProvinciaStr)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CiudadStr)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Apellido)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Cuil)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FechaNacimiento)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Genero)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Telefono)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Celular)
            </td>
            <td style="color:@(item.Estado == true ? "blue" : "red" );">
                <b>@Html.DisplayFor(modelItem => item.EstadoStr)</b>
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ProvinciaStr)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CiudadStr)
            </td>
            <td>
                <a href="#myModal" class="btnEditarOrador btn-warning btn-sm" data-toggle="modal" data-id="@item.Id">Editar</a>
                <a href="#myModal" class="btnDetalleOrador btn-info btn-sm" data-toggle="modal" data-id="@item.Id">Detalles</a>
                @if (item.EventosAsociados == false)
                {
                    <a href="#myModal" class="btnEliminarOrador btn-danger btn-sm" data-toggle="modal" data-id="@item.Id">Eliminar</a>
                }

            </td>
        </tr>
    }

</table>

<h5 class="text-muted">*No se podra eliminar Oradores que esten asociados a uno o mas Eventos.</h5>

<div id="myModal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" style="display:none;" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-body">
                <div id="modal-content">
                    cargando...
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts{
    <script src="~/Scripts/Modal/Orador.js"></script>
}