EventManager/MVC/Models/Evento/EventoABM.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Web;
using System.Web.Mvc;

namespace MVC.Models.Evento
{
    public class EventoABM : EntidadBase
    {
        [Required(AllowEmptyStrings = false, ErrorMessage = "El campo {0} es obligatorio.")]
        [StringLength(50, ErrorMessage = "El campo {0} no debe superar los {1} caracteres.")]
        public string Nombre { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "El campo {0} es obligatorio.")]
        [StringLength(150, ErrorMessage = "El campo {0} no debe superar los {1} caracteres.")]
        [DataType(DataType.MultilineText)]
        public string Descripcion { get; set; }

        [Display(Name = "Buscar Imagen")]
        public HttpPostedFileBase BuscarImagen { get; set; }

        [Required(ErrorMessage = "El campo {0} es obligatorio.")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime FechaInicio { get; set; }

        [Required(ErrorMessage = "El campo {0} es obligatorio.")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime FechaFin { get; set; }

        [Required(ErrorMessage = "El campo {0} es obliatorio.")]
        [DataType(DataType.Time)]
        [DisplayFormat(DataFormatString = "{0:hh:mm}", ApplyFormatInEditMode = true)]
        public DateTime HoraInicio { get; set; }

        [Required(ErrorMessage = "El campo {0} es obliatorio.")]
        [DataType(DataType.Time)]
        [DisplayFormat(DataFormatString = "{0:hh:mm}", ApplyFormatInEditMode = true)]
        public DateTime HoraFin { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "El campo {0} es obligatorio.")]
        [StringLength(120, ErrorMessage = "El campo {0} no debe superar los {1} caracteres.")]
        public string Lugar { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "El campo {0} es obligatorio.")]
        [StringLength(70, ErrorMessage = "El campo {0} no debe superar los {1} caracteres.")]
        public string Calle { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "El campo {0} es obligatorio.")]
        [Range(1, 9999)]
        public int Numero { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "El campo {0} es obligatorio.")]
        [StringLength(200, ErrorMessage = "El campo {0} no debe superar los {1} caracteres.")]
        [DataType(DataType.MultilineText)]
        public string Referencias { get; set; }

        [Display(Name = "Organizador")]
        public long OrganizadorId { get; set; }

        public IEnumerable<SelectListItem> Organizadores { get; set; }

        [Display(Name = "Categoria")]
        public long Categoria_EventoId { get; set; }

        public IEnumerable<SelectListItem> Categorias { get; set; }

        [Display(Name = "Orador")]
        public long OradorId { get; set; }

        public IEnumerable<SelectListItem> Oradores { get; set; }

        [Display(Name = "Provincia")]
        public long ProvinciaId { get; set; }

        public IEnumerable<SelectListItem> Provincias { get; set; }

        [Display(Name = "Ciudad")]
        public long CiudadId { get; set; }

        public IEnumerable<SelectListItem> Ciudades { get; set; }
    }
}

EventManager/MVC/Models/Evento/EventoVm.cs
using MVC.Models.Entrada;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace MVC.Models.Evento
{

    public class EventoVm : EntidadBase
    {
        //Propiedades

        public EventoVm()
        {
            Entradas = new List<EntradaVm>();

            Orador = new OradorVm();
        }

        public string Nombre { get; set; }

        public string Descripcion { get; set; }

        public string Imagen { get; set; }

        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}")]
        [Display(Name = "Fecha Inicio")]
        public DateTime FechaInicio { get; set; }

        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}")]
        [Display(Name = "Fecha Fin")]
        public DateTime FechaFin { get; set; }

        [DataType(DataType.Time)]
        [DisplayFormat(DataFormatString = "{0:hh:mm}")]
        [Display(Name = "Hora Inicio")]
        public DateTime HoraInicio { get; set; }

        [DataType(DataType.Time)]
        [DisplayFormat(DataFormatString = "{0:hh:mm}")]
        [Display(Name = "Hora Fin")]
        public DateTime HoraFin { get; set; }

        public string Lugar { get; set; }

        public string Calle { get; set; }

        [Range(1, 9999, ErrorMessage ="El valor no puede ser negativo")]
        public int Numero { get; set; }

        public string Referencias { get; set; }

        [Display(Name = "Organizador")]
        public long OrganizadorId { get; set; }

        [Display(Name = "Organizador")]
        public string OrganizadorStr { get; set; }

        [Display(Name = "Categoria")]
        public long Categoria_EventoId { get; set; }

        [Display(Name = "Categoria")]
        public string CategoriaStr { get; set; }

        [Display(Name = "Orador")]
        public long OradorId { get; set; }

        [Display(Name = "Orador")]
        public string OradorStr { get; set; }

        [Display(Name = "Provincia")]
        public long ProvinciaId { get; set; }

        [Display(Name = "Provincia")]
        public string ProvinciaStr { get; set; }

        [Display(Name = "Ciudad")]
        public long CiudadId { get; set; }

        [Display(Name = "Ciudad")]
        public string CiudadStr { get; set; }

        public string UsuarioNombre { get; set; }

        public List<EntradaVm> Entradas { get; set; }

        public EntradaVm EntradaTitulo { get; set; } // solo se usa para titulo de tablas, no usar ni asignar valores

        public OradorVm Orador { get; set; }

        public OrganizadorVm Organizador { get; set; }

        public bool TieneEntradas { get; set; }

    }
}

EventManager/MVC/Controllers/EventoController.cs
using Infraestructura;
using IServicio.Ciudad;
using IServicio.Entrada;
using IServicio.Evento;
using IServicio.Evento.Dto;
using IServicio.LineaResumen;
using IServicio.Orador;
using IServicio.Organizador;
using Microsoft.AspNet.Identity;
using MVC.Helpers;
using MVC.Helpers.ComboBox.Categoria;
using MVC.Helpers.ComboBox.Ciudad;
using MVC.Helpers.ComboBox.Orador;
using MVC.Helpers.ComboBox.Organizador;
using MVC.Helpers.ComboBox.Provincia;
using MVC.Models;
using MVC.Models.Entrada;
using MVC.Models.Evento;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using Rotativa;
using System;
using System.Net.Http;
using Newtonsoft.Json;
using Dominio.Entidades;
using IServicio.Oyente;
using System.Threading.Tasks;

namespace MVC.Controllers
{
    public class EventoController : Controller
    {
        private readonly IEventoServicio _eventoServicio;
        private readonly IEntradaServicio _entradaServicio;
        private readonly IOradorServicio _oradorServicio;
        private readonly IOrganizadorServicio _organizadorServicio;
        private readonly ILineaResumenServicio _lineaResumenServicio;
        private readonly IComboBoxCategoria _comboBoxCategoria;
        private readonly IComboBoxOrganizador _comboBoxOrganizador;
        private readonly IComboBoxOrador _comboBoxOrador;
        private readonly IComboBoxProvincia _comboBoxProvincia;
        private readonly IComboBoxCiudad _comboBoxCiudad;
        private readonly ICiudadServicio _ciudadServicio;
        private readonly IOyenteServicio _oyenteServicio;

        private EventManagerContext db = new EventManagerContext();

        public EventoController()
        {

        }

        public EventoController(IEventoServicio eventoServicio, IEntradaServicio entradaServicio, IOradorServicio oradorServicio, IOrganizadorServicio organizadorServicio, ICiudadServicio ciudadServicio, ILineaResumenServicio lineaResumenServicio, IComboBoxCategoria comboBoxCategoria, IComboBoxOrganizador comboBoxOrganizador, IComboBoxOrador comboBoxOrador, IComboBoxProvincia comboBoxProvincia, IComboBoxCiudad comboBoxCiudad, IOyenteServicio oyenteServicio)
        {
            _eventoServicio = eventoServicio;
            _entradaServicio = entradaServicio;
            _oradorServicio = oradorServicio;
            _organizadorServicio = organizadorServicio;
            _ciudadServicio = ciudadServicio;
            _lineaResumenServicio = lineaResumenServicio;
            _oyenteServicio = oyenteServicio;
            _comboBoxCategoria = comboBoxCategoria;
            _comboBoxOrganizador = comboBoxOrganizador;
            _comboBoxOrador = comboBoxOrador;
            _comboBoxProvincia = comboBoxProvincia;
            _comboBoxCiudad = comboBoxCiudad;
        }

        // GET: Evento
        public ActionResult Index(string cadenaBuscar)
        {
            //var httpClient = new HttpClient()
            //{

            //    BaseAddress = new Uri("http://localhost:64171/")
            //};

            //var json = await httpClient.GetStringAsync("http://localhost:64171/api/Evento");
            //var lista = JsonConvert.DeserializeObject<List<EventoDto>>(json);
            //return View(lista);

            //var request = await clienteHttp.GetAsync("api/Evento");

            //if (request.IsSuccessStatusCode)
            //{
            //    var resultString = request.Content.ReadAsStringAsync().Result;
            //    var listado = JsonConvert.DeserializeObject<List<Evento>>(resultString);

            var listado = _eventoServicio.GetByFilter(!string.IsNullOrEmpty(cadenaBuscar) ? cadenaBuscar : string.Empty);

            return View(listado.Select(x => new EventoVm()
            {
                Id = x.Id,
                Categoria_EventoId = x.Categoria_EventoId,
                CategoriaStr = x.CategoriaStr,
                Nombre = x.Nombre,
                Descripcion = x.Descripcion,
                Imagen = x.Imagen,
                FechaInicio = x.FechaInicio,
                FechaFin = x.FechaFin,
                HoraInicio = x.HoraInicio,
                HoraFin = x.HoraFin,
                Lugar = x.Lugar,
                Calle = x.Calle,
                Numero = x.Numero,
                Referencias = x.Referencias,
                OrganizadorId = x.OrganizadorId,
                OrganizadorStr = x.OrganizadorStr,
                OradorId = x.OradorId,
                OradorStr = x.OradorStr,
                ProvinciaId = x.ProvinciaId,
                ProvinciaStr = x.ProvinciaStr,
                CiudadId = x.CiudadId,
                CiudadStr = x.CiudadStr
            }).ToList());
        }


        public ActionResult MisEventos(string usuarioNombre)
        {
            ViewBag.userName = User.Identity.GetUserName();

            var evento = _eventoServicio.GetByUserName(usuarioNombre);

            var lista = new List<EventoVm>();

            foreach (var x in evento)
            {
                var eventoDto = new EventoVm()
                {
                    Id = x.Id,
                    Categoria_EventoId = x.Categoria_EventoId,
                    CategoriaStr = x.CategoriaStr,
                    Nombre = x.Nombre,
                    Descripcion = x.Descripcion,
                    Imagen = x.Imagen,
                    FechaInicio = x.FechaInicio,
                    FechaFin = x.FechaFin,
                    HoraInicio = x.HoraInicio,
                    HoraFin = x.HoraFin,
                    Lugar = x.Lugar,
                    Calle = x.Calle,
                    Numero = x.Numero,
                    Referencias = x.Referencias,
                    OrganizadorId = x.OrganizadorId,
                    OrganizadorStr = x.OrganizadorStr,
                    OradorId = x.OradorId,
                    OradorStr = x.OradorStr,
                    ProvinciaId = x.ProvinciaId,
                    ProvinciaStr = x.ProvinciaStr,
                    CiudadId = x.CiudadId,
                    CiudadStr = x.CiudadStr,
                    TieneEntradas = false
                };

                lista.Add(eventoDto);
            }

            foreach (var item in lista)
            {
                var entradas = _entradaServicio.GetByEventoId(item.Id);

                if (entradas.Count() > 0)
                {

                    item.TieneEntradas = true;

                }
            }
            
         

            return View(lista.Select(x => new EventoVm()
            {
                Id = x.Id,
                Categoria_EventoId = x.Categoria_EventoId,
                CategoriaStr = x.CategoriaStr,
                Nombre = x.Nombre,
                Descripcion = x.Descripcion,
                Imagen = x.Imagen,
                FechaInicio = x.FechaInicio,
                FechaFin = x.FechaFin,
                HoraInicio = x.HoraInicio,
                HoraFin = x.HoraFin,
                Lugar = x.Lugar,
                Calle = x.Calle,
                Numero = x.Numero,
                Referencias = x.Referencias,
                OrganizadorId = x.OrganizadorId,
                OrganizadorStr = x.OrganizadorStr,
                OradorId = x.OradorId,
                OradorStr = x.OradorStr,
                ProvinciaId = x.ProvinciaId,
                ProvinciaStr = x.ProvinciaStr,
                CiudadId = x.CiudadId,
                CiudadStr = x.CiudadStr,
                TieneEntradas = x.TieneEntradas

            }).ToList());
        }

        // GET: Evento/Details/5
        public ActionResult Details(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var evento = _eventoServicio.GetById(id);

            if (evento == null)
            {
                return HttpNotFound();
            }

            return View(new EventoVm()
            {
                Id = evento.Id,
                CategoriaStr = evento.CategoriaStr,
                Nombre = evento.Nombre,
                Descripcion = evento.Descripcion,
                Imagen = evento.Imagen,
                FechaInicio = evento.FechaInicio,
                FechaFin = evento.FechaFin,
                HoraInicio = evento.HoraInicio,
                HoraFin = evento.HoraFin,
                Lugar = evento.Lugar,
                Calle = evento.Calle,
                Numero = evento.Numero,
                Referencias = evento.Referencias,
                OrganizadorStr = evento.OrganizadorStr,
                OradorStr = evento.OradorStr,
                ProvinciaStr = evento.ProvinciaStr,
                CiudadStr = evento.CiudadStr
            });
        }

        public ActionResult DetalleEventoIndex(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var evento = _eventoServicio.GetById(id);
            var entradasCreadas = _entradaServicio.GetByEventoIdd(id).Count;
            var Entradas = _entradaServicio.GetByEventoIdd(id);
            var cantidadEntradas = 0;
            var fechaActual = DateTime.Today;


            if (evento == null)
            {
                return HttpNotFound();
            }

            foreach (var item in Entradas)
            {
                if (item.Cantidad > item.CantidadVendida)
                {
                    cantidadEntradas = cantidadEntradas + 1;
                }
            }

            if (entradasCreadas == 1)
            {
                foreach (var item in Entradas)
                {
                    if (fechaActual > item.FechaFinVenta)
                    {
                        var fechaFinalizada = item.FechaFinVenta;
                        ViewBag.FechaFinalizada = fechaFinalizada;
                    }
                }
            }

            ViewBag.EntradasCreadas = entradasCreadas;

EventManager/MVC/Views/Evento/Delete.cshtml
@model MVC.Models.Evento.EventoVm

@{
    Layout = null;
}

<h3>Seguro desea eliminar este evento?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Descripcion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Descripcion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Imagen)
        </dt>

        <dd>
            @if (!string.IsNullOrEmpty(Model.Imagen))
            {
                <img src="@Url.Content(Model.Imagen)" alt=" Image" style="width: 100px;height: 100px;max-width: 100%; height:auto;" />
            }
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FechaInicio)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FechaInicio)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FechaFin)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FechaFin)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HoraInicio)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HoraInicio)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HoraFin)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HoraFin)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Lugar)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Lugar)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Calle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Calle)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Numero)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Numero)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Referencias)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Referencias)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.OrganizadorStr)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OrganizadorStr)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CategoriaStr)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CategoriaStr)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.OradorStr)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OradorStr)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProvinciaStr)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProvinciaStr)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CiudadStr)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CiudadStr)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

    <div class="form-actions no-color">
        <input type="submit" value="Eliminar" class="btn btn-danger"/> 
        @Html.ActionLink("Cancelar", "MisEventos", new { usuarioNombre = HttpContext.Current.User.Identity.Name }, new { @class = "btn btn-info" })
    </div>
    }
</div>

EventManager/MVC/Views/Evento/Details.cshtml
@model MVC.Models.Evento.EventoVm

@{
    Layout = null;
}

<h2>Detalle</h2>

<div>
    <dl class="dl-horizontal">
        <h4>Evento</h4>
        <hr />
        <dt>
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Descripcion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Descripcion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Imagen)
        </dt>

        <dd>
            @if (!string.IsNullOrEmpty(Model.Imagen))
            {
                <img src="@Url.Content(Model.Imagen)" alt=" Image" style="width: 100px;height: 100px;max-width: 100%; height:auto;" />
            }
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FechaInicio)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FechaInicio)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FechaFin)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FechaFin)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HoraInicio)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HoraInicio)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HoraFin)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HoraFin)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Lugar)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Lugar)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Calle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Calle)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Numero)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Numero)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Referencias)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Referencias)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.OrganizadorStr)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OrganizadorStr)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CategoriaStr)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CategoriaStr)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.OradorStr)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OradorStr)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProvinciaStr)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProvinciaStr)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CiudadStr)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CiudadStr)
        </dd>

    </dl>
</div>

EventManager/MVC/Views/Evento/InscripcionEvento.cshtml
@model MVC.Models.Evento.EventoVm


<div class="container">

    <div class="col-md-8">
        <div class="row">
            <h2>
                @Html.DisplayFor(model => Model.Nombre)
            </h2>
            @Html.ActionLink("por " + Model.OrganizadorStr, "Details", new { id = Model.OrganizadorId })
        </div>

    </div>
    <div class="col-md-4">

    </div>

    <div class="row">

        <div class="col-md-8">
            <h2>

                @Html.DisplayFor(model => Model.Nombre)

            </h2>

            <h3>

                @Html.DisplayFor(model => Model.Organizador.ApyNom)

                @Html.DisplayFor(model => Model.FechaInicio)

                @Html.DisplayFor(model => Model.CiudadStr) 


            </h3>
           
        </div>

    </div>
</div>

EventManager/MVC/Views/Evento/MisEventos.cshtml
@model IEnumerable<MVC.Models.Evento.EventoVm>

@{
    ViewBag.Title = "MisEventos";
}

<link href="~/Content/Estilos/Reportes.css" rel="stylesheet" />

<h2>ADMINISTRA TUS EVENTOS</h2>


@using (Html.BeginForm("MisEventos", "Evento", new { usuarioNombre = ViewBag.userName }, FormMethod.Post))
{
    <p>
        <div class="row">
            <div class="col-md-12">
                <a id="btnNuevo" data-toggle="modal" href="#myModal" class="btn btn-primary btn-lg">Crear Evento</a>
            </div>
        </div>
    </p>

    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FechaInicio)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.HoraInicio)
            </th>

            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            var numero = 0;

            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Nombre)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.FechaInicio)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.HoraInicio)
                </td>
                <td>

                        @if (item.TieneEntradas)
                        {
                            numero = 1;
                        }
                 
                    @Html.ActionLink("Administrar", "AdministrarEvento", "Evento", new { id = item.Id }, new { @class = "btn btn-primary btn-xs" })
                    <a href="#myModal" class="btnDetalle btn-info btn-sm" x data-toggle="modal" data-id="@item.Id">Detalle</a>

                    @if (numero == 0)
                    {
                        <a href="#myModal" class="btnEditar btn-warning btn-sm" data-toggle="modal" data-id="@item.Id">Editar</a>
                        <a href="#myModal" class="btnEliminar btn-danger btn-sm" x data-toggle="modal" data-id="@item.Id">Eliminar</a>
                    }

                </td>
            </tr>
        }


    </table>

    <h5 class="text-muted">* Recuerda que si un evento contiene entradas no se podra editarlo ni eliminarlo.</h5>

}

<div id="myModal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" style="overflow-y: scroll;" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-body">
                <div id="modal-content">
                    cargando...
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts{
    <script src="~/Scripts/Modal/Evento.js"></script>
}