EventManager/MVC/Models/Entrada/EntradaVm.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace MVC.Models.Entrada
{

    public class EntradaVm : EntidadBase
    {
        //Propiedades

        [Required(AllowEmptyStrings = false, ErrorMessage = "El campo {0} es obligatorio.")]
        [StringLength(50, ErrorMessage = "El campo {0} no debe superar los {1} caracteres.")]
        public string Nombre { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "El campo {0} es obligatorio.")]
        [StringLength(150, ErrorMessage = "El campo {0} no debe superar los {1} caracteres.")]
        [DataType(DataType.MultilineText)]
        public string Descripcion { get; set; }

        [Required(ErrorMessage = "El campo {0} es obligatorio.")]
        [Range(1, 9999)]
        public int Cantidad { get; set; }

        public decimal? Precio { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "El campo {0} es obligatorio.")]
        [Display(Name = "Tipo de Entrada")]
        public string TipoEntrada { get; set; }

        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        [Display(Name = "Fecha Inicio Venta")]
        public DateTime FechaInicioVenta { get; set; }

        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        [Display(Name = "Fecha Fin Venta")]
        public DateTime FechaFinVenta { get; set; }

        [Display(Name = "Cantidad Max por Compra")]
        [Range(1, 9999)]
        public int CantidadMaximaPorCompra { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "El campo {0} es obligatorio.")]
        [Display(Name = "Canal de Venta")]
        public string CanalDeVentas { get; set; }

        [Display(Name = "Evento")]
        public long? EventoId { get; set; }

        [Display(Name = "Evento")]
        public string EventoStr { get; set; }

        [Display(Name = "Precio")]
        public string PrecioStr { get; set; }

        [Display(Name = "Cantidad")]
        public string CantidadStr { get; set; } // solo se usa para ver la cantidad de entradas disponilbes aun!!

        public int CantSeleccionada { get; set; }

        public int CantVendida { get; set; }

    }
}

EventManager/MVC/Controllers/EntradasController.cs
using Infraestructura;
using IServicio.Entrada;
using IServicio.Entrada.Dto;
using IServicio.Evento;
using IServicio.LineaResumen;
using MVC.Models.Entrada;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web.Mvc;

namespace MVC.Controllers
{
    public class EntradasController : Controller
    {
        private EventManagerContext db = new EventManagerContext();

        private readonly IEntradaServicio _entradaServicio;
        private readonly IEventoServicio _eventoServicio;
        private readonly ILineaResumenServicio _lineaResumenServicio;

        public EntradasController()
        {

        }

        public EntradasController(IEntradaServicio entradaServicio, IEventoServicio eventoServicio, ILineaResumenServicio lineaResumenServicio)
        {
            _entradaServicio = entradaServicio;
            _eventoServicio = eventoServicio;
            _lineaResumenServicio = lineaResumenServicio;
        }

        // GET: Entradas/Details/5
        public ActionResult Details(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var entrada = _entradaServicio.GetById(id);

            if (entrada == null)
            {
                return HttpNotFound();
            }
            return View(new EntradaVm()
            {
                Id = entrada.Id,
                Nombre = entrada.Nombre,
                Descripcion = entrada.Descripcion,
                FechaInicioVenta = entrada.FechaInicioVenta,
                FechaFinVenta = entrada.FechaFinVenta,
                Precio = entrada.Precio,
                Cantidad = entrada.Cantidad,
                CantidadMaximaPorCompra = entrada.CantidadMaximaPorCompra,
                CanalDeVentas = entrada.CanalDeVentas,
                TipoEntrada = entrada.TipoEntrada
            });
        }

        // GET: Entradas/Create
        [HttpGet]
        public ActionResult Create(long id)
        {
            var eventoId = id;

            List<SelectListItem> listaCanalVenta = new List<SelectListItem>()
            {
                new SelectListItem{Text = "Online" , Value = "Online"},
                new SelectListItem{Text = "Boleteria" , Value = "Boleteria"}
            };

            List<SelectListItem> listaTipoEntrada = new List<SelectListItem>()
            {
                new SelectListItem{Text = "Paga" , Value = "Paga"},
                new SelectListItem{Text = "Gratuita" , Value = "Gratuita"}
            };

            ViewBag.CanalventaId = listaCanalVenta;
            ViewBag.TipoEntradaId = listaTipoEntrada;

            return View(new EntradaVm()
            {
                EventoId = eventoId
            });
        }

        // POST: Entradas/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(EntradaVm entradaVm, long eventoId)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var precio = entradaVm.Precio;

                    var entrada = ConvertirEntradaDto(entradaVm, precio, eventoId);

                    _entradaServicio.Add(entrada);
                }
            }

            catch (Exception ex)
            {
                if (ex.InnerException != null &&
                    ex.InnerException.InnerException != null &&
                    ex.InnerException.InnerException.Message.Contains("_Index"))
                {
                    ModelState.AddModelError(string.Empty, "No se pudo crear el registro por que ya existe");
                }
                else
                {
                    ModelState.AddModelError(string.Empty, ex.Message);
                }

                List<SelectListItem> listaCanalVenta = new List<SelectListItem>()
            {
                new SelectListItem{Text = "Online" , Value = "Online"},
                new SelectListItem{Text = "Boleteria" , Value = "Boleteria"}
            };

                List<SelectListItem> listaTipoEntrada = new List<SelectListItem>()
            {
                new SelectListItem{Text = "Paga" , Value = "Paga"},
                new SelectListItem{Text = "Gratuita" , Value = "Gratuita"}
            };

                ViewBag.CanalventaId = listaCanalVenta;
                ViewBag.TipoEntradaId = listaTipoEntrada;

                return View(entradaVm);
            }
            

            return RedirectToAction("AdministrarEvento", "Evento", new { id = eventoId });

        }

        // GET: Entradas/Edit/5
        public ActionResult Edit(long id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var entrada = _entradaServicio.GetById(id);

            if (entrada == null)
            {
                return HttpNotFound();
            }

            List<SelectListItem> listaCanalVenta = new List<SelectListItem>()
            {
                new SelectListItem{Text = "Online" , Value = "Online"},
                new SelectListItem{Text = "Boleteria" , Value = "Boleteria"}
            };

            List<SelectListItem> listaTipoEntrada = new List<SelectListItem>()
            {
                new SelectListItem{Text = "Paga" , Value = "Paga"},
                new SelectListItem{Text = "Gratuita" , Value = "Gratuita"}
            };

            ViewBag.CanalventaId = listaCanalVenta;
            ViewBag.TipoEntradaId = listaTipoEntrada;
            ViewData["id"] = entrada.EventoId;
            ViewBag.CantidadInicial = entrada.Cantidad;
            ViewBag.CantMaximaInicial = entrada.CantidadMaximaPorCompra;

            return View(new EntradaVm()
            {
                Nombre = entrada.Nombre,
                Descripcion = entrada.Descripcion,
                FechaInicioVenta = entrada.FechaInicioVenta,
                FechaFinVenta = entrada.FechaFinVenta,
                Precio = entrada.Precio,
                Cantidad = entrada.Cantidad,
                CantidadMaximaPorCompra = entrada.CantidadMaximaPorCompra,
                CanalDeVentas = entrada.CanalDeVentas,
                TipoEntrada = entrada.TipoEntrada,
                EventoId = entrada.EventoId

            });
        }

        // POST: Entradas/Edit/5
        [HttpPost]
        public ActionResult Edit(EntradaVm entradaVm, long eventoId)
        {
            var precios = entradaVm.Precio;

            Convert.ToDecimal(precios);

            try
            {
             
                if (ModelState.IsValid)
                {
                    var precio = precios;

                    var entrada = ConvertirEntradaDto(entradaVm, precio, eventoId);

                    _entradaServicio.Update(entrada);

                }

            }

            catch (Exception ex)
            {
                if (ex.InnerException != null &&
                    ex.InnerException.InnerException != null &&
                    ex.InnerException.InnerException.Message.Contains("_Index"))
                {
                    ModelState.AddModelError(string.Empty, "No se pudo crear el registro por que ya existe");
                }
                else
                {
                    ModelState.AddModelError(string.Empty, ex.Message);
                }

                List<SelectListItem> listaCanalVenta = new List<SelectListItem>()
            {
                new SelectListItem{Text = "Online" , Value = "Online"},
                new SelectListItem{Text = "Boleteria" , Value = "Boleteria"}
            };

                List<SelectListItem> listaTipoEntrada = new List<SelectListItem>()
            {
                new SelectListItem{Text = "Paga" , Value = "Paga"},
                new SelectListItem{Text = "Gratuita" , Value = "Gratuita"}
            };

                ViewBag.CanalventaId = listaCanalVenta;
                ViewBag.TipoEntradaId = listaTipoEntrada;

                return View(entradaVm);
            }

            return RedirectToAction("AdministrarEvento", "Evento", new { id = eventoId });
        }

        // GET: Entradas/Delete/5
        public ActionResult Delete(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var entrada = _entradaServicio.GetById(id);

            if (entrada == null)
            {
                return HttpNotFound();
            }

            return View(new EntradaVm()
            {
                Id = entrada.Id,
                Nombre = entrada.Nombre,
                Descripcion = entrada.Descripcion,
                FechaInicioVenta = entrada.FechaInicioVenta,
                FechaFinVenta = entrada.FechaFinVenta,
                Precio = entrada.Precio,
                Cantidad = entrada.Cantidad,
                CantidadMaximaPorCompra = entrada.CantidadMaximaPorCompra,
                CanalDeVentas = entrada.CanalDeVentas,
                TipoEntrada = entrada.TipoEntrada,
                EventoId = entrada.EventoId
            });
        }

        // POST: Entradas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(long id, EntradaVm entradaVm)
        {
            var evento = _entradaServicio.GetById(id);

            try
            {
                _entradaServicio.Delete(id);
            }
            catch (Exception ex)
            {
                if (ex.InnerException != null &&
                    ex.InnerException.InnerException != null &&

EventManager/MVC/Views/Entradas/Delete.cshtml
@model MVC.Models.Entrada.EntradaVm

@{
    Layout = null;
}

<h3>Seguro desea eliminar esta Entrada?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Descripcion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Descripcion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Cantidad)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cantidad)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TipoEntrada)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TipoEntrada)
        </dd>

        @if (Model.TipoEntrada == "Paga")
        {
            <dt>
                @Html.DisplayNameFor(model => model.Precio)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Precio)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.FechaInicioVenta)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.FechaInicioVenta)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.FechaFinVenta)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.FechaFinVenta)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.CantidadMaximaPorCompra)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.CantidadMaximaPorCompra)
            </dd>
        }

        <dt>
            @Html.DisplayNameFor(model => model.CanalDeVentas)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CanalDeVentas)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        <div class="form-actions no-color">

            <input type="submit" value="Eliminar" class="btn btn-danger" />

            @Html.ActionLink("Cancelar", "AdministrarEvento", "Evento", new { id = Model.EventoId }, new { @class = "btn btn-info" })
        </div>
    }
</div>

EventManager/MVC/Views/Entradas/Details.cshtml
@model MVC.Models.Entrada.EntradaVm

@{
    Layout = null;
}

<h2>Detalles</h2>

<div>
    <dl class="dl-horizontal">
        <h4>Entrada</h4>
        <hr />
        <dt>
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Descripcion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Descripcion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Cantidad)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cantidad)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Precio)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Precio)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TipoEntrada)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TipoEntrada)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FechaInicioVenta)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FechaInicioVenta)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FechaFinVenta)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FechaFinVenta)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CantidadMaximaPorCompra)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CantidadMaximaPorCompra)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CanalDeVentas)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CanalDeVentas)
        </dd>

    </dl>
</div>

EventManager/MVC/Views/Entradas/EntradasPorEvento.cshtml
@model IList<MVC.Models.Entrada.EntradaVm>
@{
    Layout = null;
}

<link href="~/Content/Estilos/EntradasModal.css" rel="stylesheet" />
@{ var nuevo = 0; }
@{ var suma = 0; }
@{ var fechaActual = ViewBag.FechaActual; }

@using (Html.BeginForm("EntradasPorEvento", "Entradas", FormMethod.Post, new { id = @ViewData["id"] }))

{
    @Html.AntiForgeryToken()

<div class="form-horizontal modelo">

    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    @for (int i = 0; i < Model.Count(); i++)
    {
    <div class="form-group bs-callout bs-callout-primary contenedor">

        <div class="col-md-8">

            @Html.HiddenFor(modelItem => modelItem[i].Id)

            <div id="precioValor">

                <h4>

                    @Html.TextBoxFor(modelItem => modelItem[i].Nombre
                    ,new { @readonly = true, style = "border: 0; outline: none;" })

                </h4>

            </div>

            <input type="hidden" value="@Model[i].Precio" class="precio">

            <span id="precio">

                @Html.TextBoxFor(modelItem => modelItem[i].PrecioStr
                , new { @readonly = true, style = "border: none; outline: none;", @id = "precio" })

            </span>

            <br />

            @{var fechaInicio = Model[i].FechaInicioVenta.ToShortDateString();}
            @{var fechaFin = Model[i].FechaFinVenta.ToShortDateString();}

            @if (Model[i].FechaInicioVenta > fechaActual)
            {
                if (Model[i].Precio > 0)
                {
                    <h6 class="text-muted"> Disponible a partir de @fechaInicio </h6>
                }

                if (Model[i].Precio == 0)
                {
                    <h6 class="text-muted"> Disponible a partir de @fechaInicio</h6>
                }

            }

            else
            {
                if (Model[i].FechaFinVenta >= fechaActual)
                {
                    if (Model[i].Precio > 0)
                    {
                        <h6 class="text-muted"> Disponible hasta @fechaFin </h6>
                    }

                    if (Model[i].Precio == 0)
                    {
                        <h6 class="text-muted"> Disponible hasta @fechaFin</h6>
                    }

                }

                else
                {
                    if (Model[i].Precio > 0)
                    {
                        <h6 class="text-muted"> La venta Finalizo el @fechaFin </h6>
                    }

                    if (Model[i].Precio == 0)
                    {
                        <h6 class="text-muted"> La Adquisicion Finalizo el @fechaFin</h6>
                    }

                }
            }

        </div>

        @if (Model.Count() == 1)
        {
            if (Model[i].FechaInicioVenta > fechaActual)
            {
                @Html.DropDownListFor(modelItem => modelItem[i].Cantidad
                , new SelectList(Enumerable.Range(0, 1))
                , new { @class = "form-control cantidad", @style = "display:none" })
            }

            else
            {
                <div class="col-lg-2" id="cant">

                    @Html.DropDownListFor(modelItem => modelItem[i].Cantidad
                    , new SelectList(Enumerable.Range(1, (Model[i].CantidadMaximaPorCompra)))
                    , new { @class = "form-control cantidad" })

                </div>
            }

        }

        @if (Model.Count() > 1)
        {

                <div class="col-lg-2" id="cant">

                    @if (Model[i].FechaInicioVenta > fechaActual)
                    {
                        @Html.DropDownListFor(modelItem => modelItem[i].Cantidad
                        , new SelectList(Enumerable.Range(0, 1))
                        , new { @class = "form-control cantidad", @style = "display:none" })
                    }

                    else
                    {
                        if (Model[i].FechaFinVenta >= fechaActual)
                        {

                            if (Model[i].CantidadMaximaPorCompra > 0)

                            {
                                @Html.DropDownListFor(modelItem => modelItem[i].Cantidad
                                , new SelectList(Enumerable.Range(0, (Model[i].CantidadMaximaPorCompra + 1)))
                                , new { @class = "form-control cantidad" })
                            }

                            if (Model[i].CantidadMaximaPorCompra <= 0)
                            {

                                <h3 class="text-muted"> Agotadas!</h3>

                                @Html.DropDownListFor(modelItem => modelItem[i].Cantidad
                                , new SelectList(Enumerable.Range(0, 1))
                                , new { @class = "form-control cantidad", @style = "display:none" })

                            }
                        }

                        else
                        {
                            <h3 class="text-muted"> Venta Finalizada!</h3>

                            @Html.DropDownListFor(modelItem => modelItem[i].Cantidad
                               , new SelectList(Enumerable.Range(0, 1))
                               , new { @class = "form-control cantidad", @style = "display:none" })
                        }
                    }

                </div>


        }

    </div>


     }



    <div class="form-group">
        <div class="col-md-3">
            <span id="cantSel">
                @Html.DisplayFor(modelItem => nuevo)
            </span>
        </div>

        <div class="col-md-3">
            <span id="totalEntradas">
                @Html.DisplayFor(modelItem => suma)
            </span>
        </div>

        <div class="col-md-4">

            <input type="submit" value="Confirmar" id="confirmar" class="btn btn-success btn-lg btn-block" />

        </div>

    </div>
</div>

 }

<script type="text/javascript">


    $(document).ready(function () {

        var total = 0;
        var cantidadTotal = 0;

        var combos = $(".cantidad");

        ///////////////////////////////
        //// vaalidaciones campos ////
        /////////////////////////////

        combos.each(function () {

            var cantidad = $(this).val();

            cantidadTotal = cantidadTotal + parseInt(cantidad);

            console.log(cantidad);

            var padre = this.parentElement.parentElement
            var precio = padre.getElementsByClassName("precio")[0].value;

            var n = precio.replace(",", ".");
            if (n >= 0.5)

                total = total + n * cantidad;

            console.log(total);
            console.log(cantidadTotal);

        })
        $("#cantSel").text("Cantidad: " + cantidadTotal)

        $("#totalEntradas").text("$ " + total).css('font-weight', 'bold');;


        $(".cantidad").change(function () {

            var total = 0;
            var cantidadTotal = 0;

            var combos = $(".cantidad");
            combos.each(function () {

                var cantidad = $(this).val();

                cantidadTotal = cantidadTotal + parseInt(cantidad);

                console.log(cantidad);

                var padre = this.parentElement.parentElement
                var precio = padre.getElementsByClassName("precio")[0].value;

                var n = precio.replace(",", ".");
                if (n >= 0.5)

                    total = total + n * cantidad;

                console.log(total);
                console.log(cantidadTotal);

            })
            $("#cantSel").text("Cantidad: " + cantidadTotal);

            $("#totalEntradas").text("$" + total);
        });

        $("#confirmar").click(function () {

            if ($("#cantSel").text() == "Cantidad: " + "0") {
                alert("Debe Seleccionar por lo menos 1 entrada para poder continuar");

                return false;
            }

        })

    })

</script>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

EventManager/MVC/Views/Entradas/Index.cshtml
@model IEnumerable<MVC.Models.Entrada.EntradaVm>

@{
    ViewBag.Title = "Entradas";
}
<link href="~/Content/Estilos/Reportes.css" rel="stylesheet" />
<h2>Index</h2>

<p>
    @Html.ActionLink("Agregar", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Nombre)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Cantidad)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Precio)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FechaInicioVenta)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FechaFinVenta)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CanalDeVentas)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Nombre)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Cantidad)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Precio)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FechaInicioVenta)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FechaFinVenta)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CanalDeVentas)
        </td>
        <td>
            @Html.ActionLink("Editar", "Edit", new { id = item.Id }, new {@class = "btn btn-warning"}) |
            @Html.ActionLink("Detalles", "Details", new { id=item.Id }, new { @class = "btn btn-info" }) |
            @Html.ActionLink("Eliminar", "Delete", new { id=item.Id }, new { @class = "btn btn-danger" })
        </td>
    </tr>
}

</table>

EventManager/MVC/Views/Entradas/View.cshtml
@model IList<MVC.Models.Entrada.EntradaVm>
@{
    Layout = null;
}

<link href="~/Content/Estilos/EntradasModal.css" rel="stylesheet" />
@{ var nuevo = 0; }
@{ var suma = 0; }

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal modelo">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        @foreach (var item in Model)
        {
            <div class="form-group bs-callout bs-callout-primary contenedor">
                <div class="col-md-8">
                    <div id="precioValor">
                        <h4>@Html.DisplayFor(modelItem => item.Nombre)</h4>
                    </div>
                    <input type="hidden" value="@item.Precio" class="precio">

                    <span id="precio">
                        @Html.DisplayFor(modelItem => item.Precio)
                    </span>

                </div>
                <div class="col-lg-2">
                    <select id="cant" class="form-control cantidad">
                        @foreach (var cant in Enumerable.Range(1, item.Cantidad))
                        {
                            <option value="@cant">@cant</option>
                        }

                    </select>
                </div>
            </div>
        }
        <div class="form-group">
            <div class="col-md-3">
                <span id="cantSel">
                    @Html.DisplayFor(modelItem => nuevo)
                </span>
            </div>
            <div class="col-md-3">
                <span id="totalEntradas">
                    @Html.DisplayFor(modelItem => suma)
                </span>
            </div>
            <div class="col-md-4">

                <a id="confirmar" class="btn btn-primary btn-lg btn-block">Confirmar</a>
             
            </div>
        </div>
    </div>
}

<script type="text/javascript">


    $(document).ready(function () {

        var cantidadmax = $(".CantidadMaximaPorCompra").val();
        console.log(cantidadmax)

        $("#confirmar").click(function () {

            $.ajax({
                    type: 'POST',
                    url: '@Url.Action("InscripcionEvento")',
                    dataType: 'json',
                    data: { cantidad: $("#cantSel").val(), total: $("#totalEntradas").val() },
                    success: function (data) {

                    },
                });

        })

        var valorSeleccionado = $(this).children("option:selected").val();


        if (valorSeleccionado != undefined) {
            $("#cantSel").text("Cantidad: " + valorSeleccionado);
        }
        else {
            $("#cantSel").text("Cantidad: 0");
        }

        var precio = $("#precio").text();
        var total = precio * valorSeleccionado;

        $("#totalEntradas").text("$" + total);

        $(".cantidad").change(function () {

            var total = 0;
            var cantidadTotal = 0;

            var combos = $(".cantidad");
            combos.each(function () {


                var cantidad = $(this).val();

                cantidadTotal = cantidadTotal + parseInt(cantidad);

                console.log(cantidad);

                var padre = this.parentElement.parentElement
                var precio = padre.getElementsByClassName("precio")[0].value;

                total = total + precio * cantidad;

                console.log(total);
                console.log(cantidadTotal);

            })
            $("#cantSel").text("Cantidad: " + cantidadTotal);

            $("#totalEntradas").text("$" + total);
        });

    })
</script>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}